scan:
  recency_days: 14
  keywords:
    - logistics
    - supply chain
    - procurement
    - operations
    - warehouse
    - transport
    - fleet
    - country logistics
    - head of logistics
    - inventory
    - warehouse manager
    - operations manager
    - supply-chain manager
  orgs:
    - name: "Action contre la Faim (ACF)"
      url: "https://www.actioncontrelafaim.org/en/our-job-offers/"

    - name: "World Food Programme (WFP)"
      url: "https://www.wfp.org/careers"

    - name: "Clinton Health Access Initiative (CHAI)"
      url: "https://careers-chai.icims.com/jobs"

    - name: "International Organization for Migration (IOM)"
      url: "https://recruit.iom.int/"

    - name: "UNHCR"
      url: "https://www.unhcr.org/careers.html"

    - name: "Médecins Sans Frontières (MSF)"
      url: "https://www.msf.org/work-msf"

    - name: "Jhpiego"
      url: "https://jhpiego.org/careers/"

    - name: "Amref Health Africa"
      url: "https://amref.org/vacancies/"

    - name: "Save the Children (International)"
      url: "https://www.savethechildren.net/careers"

    - name: "International Rescue Committee (IRC)"
      url: "https://careers.rescue.org/"

    - name: "FHI 360"
      url: "https://www.fhi360.org/join-our-team/"

    - name: "CARE International"
      url: "https://www.care.org/careers/"

    - name: "WHO (World Health Organization)"
      url: "https://www.who.int/careers"

    - name: "PATH"
      url: "https://www.path.org/who-we-are/careers/"

    - name: "JSI (John Snow, Inc.)"
      url: "https://careers.jsi.com/JSIInternet/Careers/index.cfm"

email:
  provider: smtp
  from: "usiaphreteheri@gmail.com"
  to:
    - "usiaphreteheri@gmail.com"
  subject_prefix: "[Job Alert]"

smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "usiaphreteheri@gmail.com"
  password: "ubxnvmhftlbebuwb"
