scan:
  recency_days: 14
  allow_undated_jobs: true
  keywords:
    - logistics
    - supply chain
    - procurement
    - operations
    - warehouse
    - transport
    - fleet
    - country logistics
    - head of logistics
    - inventory
    - warehouse manager
    - operations manager
    - supply-chain manager
  orgs:
    - name: "Action contre la Faim (ACF)"
      url: "https://recrutement.actioncontrelafaim.org/en/our-offers/"

    - name: "World Food Programme (WFP)"
      url: "https://wd3.myworkdaysite.com/en-GB/recruiting/wfp/job_openings"

    - name: "Clinton Health Access Initiative (CHAI)"
      url: "https://careers-chai.icims.com/jobs"

    - name: "International Organization for Migration (IOM)"
      url: "https://fa-evlj-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs"

    - name: "UNHCR"
      url: "https://unhcr.wd3.myworkdayjobs.com/en-GB/External"

    - name: "Médecins Sans Frontières (MSF)"
      url: "https://www.msf.org/jobs"

    - name: "Jhpiego"
      url: "https://jobs-jhpiego.icims.com/jobs/search"

    - name: "Amref Health Africa"
      url: "https://amref.org/vacancies/"

    - name: "Save the Children (International)"
      url: "https://www.savethechildren.net/careers/apply"

    - name: "International Rescue Committee (IRC)"
      url: "https://theirc.wd1.myworkdayjobs.com/en-US/External_Careers"

    - name: "FHI 360"
      url: "https://fhi.wd1.myworkdayjobs.com/en-GB/FHI_360_External_Career_Portal"

    - name: "CARE International"
      url: "https://phg.tbe.taleo.net/phg02/ats/careers/v2/searchResults?org=CAREUSA&cws=52"

    - name: "WHO (World Health Organization)"
      url: "https://careers.who.int/careersection/ex/jobsearch.ftl"

    - name: "PATH"
      url: "https://info.path.org/myworkdayjobs/external?_gl=1*1uvyn5h*_gcl_au*MTU2NDQ0NjQ0MC4xNzY0NTk5NTI2*_ga*ODM4NTM1Mjk2LjE3NjQ1OTk1Mjc.*_ga_YBSE7ZKDQM*czE3NjQ1OTk1MjYkbzEkZzEkdDE3NjQ2MDExODUkajYwJGwwJGgw"

    - name: "JSI (John Snow, Inc.)"
      url: "https://careers.jsi.com/JSIInternet/Careers/index.cfm"

email:
  provider: smtp
  from: "usiaphreteheri@gmail.com"
  to:
    - "usiaphreteheri@gmail.com"
  subject_prefix: "[Job Alert]"

smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "usiaphreteheri@gmail.com"
  password: "ubxnvmhftlbebuwb"
